### ISSUE TITLE
[Question] how to use finializer

### ISSUE THREAD

**Issue by Inc0n** [playXE/cgc#2]
In the example code, we have the following code:
```
impl Finalizer for Foo {
    fn finalize(&mut self) {
        println!("finalize foo {}", self.x);
    }
}
```
I am not 100% certain about the need and usage of `Finializer`. Is it similar to destructors in other languages? If so, what procedures do we follow to destruct our objects?
Please provide some more insights.
Thanks!

**Comment by playXE** [comment]
It is used exactly like `Drop`, but `finalize` invoked only when GC tries to delete object.
You may just do `impl Finalizer for Foo {}` and do not care about it if you do not need to know is your object deleted by GC or no.

**Comment by Inc0n** [comment]
Okay, that is most helpful
